version: "3.8"
services:
  registrationdb:
    build: ./database/
    networks:
        - course_reg_nw
  app:
    build: ./app/
    ports:
     - "8082:8082"
    networks:
        - course_reg_nw
    depends_on:
        - registrationdb
networks:
   course_reg_nw:
    name: course_reg_nw
    external: true